version: '2.3'

services:
  wordpress:
    image: wordpress:6.3.2
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    ports:
      - ${IP}:${PORT}:80
    volumes:
      - ../php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:8.2.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: always
